server:
  port: 8082
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: contas
  data:
    mongodb:
      authentication-database: admin
      host: ${MONGO_HOST}
      port:
      database: tech-challenge-product
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}

swagger:
  title: Api de cadastro de contas
  version: 1.0
  description: APi para cadastro e pesquisa de Contas
  contact:
    name: Daniel A. Correa
    email: daniel.cor@outlook.com

api:
  security:
    token:
      secret: 123445