name: Java CI with Maven
on:
  push:
    branches:
      [main]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: mvn clean install

  docker-pull-image:
    name: Pull Image Docker Hub
    #if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login Docker Hub
        run: docker login -u daniel36 -p ${{ secrets.PASSWORD_DOCKER_HUB }}
      - name: Build docker image
        run: docker build -t daniel36/contas:${{github.run_number}} .
      - name: Push image docker
        run: docker push daniel36/contas:${{github.run_number}}

      - name: Build docker image latest
        run: docker build -t daniel36/contas:latest .
      - name: Push image docker latest
        run: docker push daniel36/contas:latest
